# Generated by Django 5.0.3 on 2024-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
